import type { HelpType, OfferType, UrgencyLevel, RequestStatus, PersonStatus, InfoCategory, PoiType, IncidentType, ProtectionType, ObservedState, HealthRequestType, BloodType, HealthPriority, CommunityKitchenNeedType, CampaignType, VerificationLevel } from '../types'

export const HELP_TYPES: { value: HelpType; label: string }[] = [
  { value: 'water', label: 'Agua' },
  { value: 'food', label: 'Comida' },
  { value: 'medicine', label: 'Medicinas' },
  { value: 'shelter', label: 'Refugio' },
  { value: 'rescue', label: 'Rescate' },
  { value: 'electricity', label: 'Electricidad' },
  { value: 'communication', label: 'Comunicacion' },
  { value: 'transport', label: 'Transporte' },
  { value: 'other', label: 'Otro' },
]

export const OFFER_TYPES: { value: OfferType; label: string }[] = [
  { value: 'food', label: 'Tengo comida' },
  { value: 'water', label: 'Tengo agua' },
  { value: 'kitchen', label: 'Tengo cocina' },
  { value: 'gas', label: 'Tengo gas' },
  { value: 'vehicle', label: 'Tengo vehiculo' },
  { value: 'fuel', label: 'Tengo combustible' },
  { value: 'tools', label: 'Tengo herramientas' },
  { value: 'internet', label: 'Tengo internet' },
  { value: 'starlink', label: 'Tengo Starlink' },
  { value: 'electricity', label: 'Tengo electricidad' },
  { value: 'generator', label: 'Tengo generador' },
  { value: 'doctor', label: 'Tengo medico' },
  { value: 'nurse', label: 'Tengo enfermero' },
  { value: 'psychologist', label: 'Tengo psicologo' },
  { value: 'rescuers', label: 'Tengo rescatistas' },
  { value: 'volunteers', label: 'Tengo voluntarios' },
  { value: 'shelter_space', label: 'Tengo espacio para alojar' },
  { value: 'medicine', label: 'Tengo medicamentos' },
  { value: 'clothing', label: 'Tengo ropa' },
  { value: 'machinery', label: 'Tengo maquinaria' },
]

export const URGENCY_LEVELS: { value: UrgencyLevel; label: string; color: string }[] = [
  { value: 'low', label: 'Baja', color: '#22c55e' },
  { value: 'medium', label: 'Media', color: '#eab308' },
  { value: 'high', label: 'Alta', color: '#f97316' },
  { value: 'critical', label: 'Critica', color: '#dc2626' },
]

export const REQUEST_STATUSES: { value: RequestStatus; label: string; color: string; emoji: string }[] = [
  { value: 'pending', label: 'Pendiente', color: '#dc2626', emoji: '🔴' },
  { value: 'in_process', label: 'En proceso', color: '#eab308', emoji: '🟡' },
  { value: 'attended', label: 'Atendido', color: '#22c55e', emoji: '🟢' },
  { value: 'closed', label: 'Cerrado', color: '#6b7280', emoji: '⚫' },
]

export const PERSON_STATUSES: { value: PersonStatus; label: string; color: string }[] = [
  { value: 'unknown', label: 'Desconocido', color: '#6b7280' },
  { value: 'ok', label: 'Esta bien', color: '#22c55e' },
  { value: 'injured', label: 'Herido', color: '#f97316' },
  { value: 'medical_attention', label: 'Necesita atencion medica', color: '#dc2626' },
  { value: 'transferred', label: 'Fue trasladado', color: '#3b82f6' },
  { value: 'with_family', label: 'Con familiares', color: '#22c55e' },
]

export const INFO_CATEGORIES: { value: InfoCategory; label: string; icon: string }[] = [
  { value: 'hospital', label: 'Hospitales', icon: '🏥' },
  { value: 'road', label: 'Vias cerradas', icon: '🚧' },
  { value: 'shelter', label: 'Refugios', icon: '🏠' },
  { value: 'distribution', label: 'Centros de distribucion', icon: '📦' },
  { value: 'services', label: 'Servicios', icon: '⚡' },
  { value: 'weather', label: 'Clima', icon: '🌧️' },
  { value: 'official', label: 'Comunicados oficiales', icon: '📢' },
  { value: 'transport', label: 'Transporte', icon: '🚍' },
  { value: 'alert', label: 'Alertas', icon: '🚨' },
  { value: 'general', label: 'General', icon: '📋' },
]

export const INCIDENT_TYPES: { value: IncidentType; label: string; icon: string }[] = [
  { value: 'bridge_down', label: 'Puente caido', icon: '🌉' },
  { value: 'landslide', label: 'Derrumbe / Deslizamiento', icon: '⛰️' },
  { value: 'flood', label: 'Inundacion', icon: '🌊' },
  { value: 'fire', label: 'Incendio', icon: '🔥' },
  { value: 'fallen_tree', label: 'Arbol caido', icon: '🌳' },
  { value: 'electric_cable', label: 'Cable electrico caido', icon: '⚡' },
  { value: 'gas_leak', label: 'Fuga de gas', icon: '💨' },
  { value: 'collapsed_building', label: 'Edificio colapsado', icon: '🏚️' },
  { value: 'blocked_street', label: 'Calle bloqueada', icon: '🚧' },
  { value: 'no_electricity', label: 'Sin electricidad', icon: '🔌' },
  { value: 'no_water', label: 'Sin agua', icon: '🚰' },
  { value: 'other', label: 'Otro', icon: '📍' },
]

export const PROTECTION_TYPES: { value: ProtectionType; label: string; icon: string }[] = [
  { value: 'child_at_risk', label: 'Menor en riesgo', icon: '👶' },
  { value: 'elderly_at_risk', label: 'Adulto mayor en riesgo', icon: '👴' },
  { value: 'disabled_at_risk', label: 'Persona con discapacidad en riesgo', icon: '♿' },
  { value: 'disoriented_person', label: 'Persona desorientada', icon: '🧭' },
  { value: 'vulnerable_immediate', label: 'Persona vulnerable requiere ayuda inmediata', icon: '🚨' },
  { value: 'lost_pet', label: 'Mascota perdida', icon: '🐶' },
  { value: 'found_pet', label: 'Mascota encontrada', icon: '🐕' },
  { value: 'animal_at_risk', label: 'Animal en riesgo', icon: '🐾' },
]

export const OBSERVED_STATES: { value: ObservedState; label: string }[] = [
  { value: 'alone', label: 'Solo/a' },
  { value: 'injured', label: 'Herido/a' },
  { value: 'needs_help', label: 'Necesita ayuda' },
  { value: 'disoriented', label: 'Desorientado/a' },
  { value: 'accompanied', label: 'Acompanado/a' },
  { value: 'unknown', label: 'No se sabe' },
]

export const PROTECTION_STATUSES: { value: string; label: string; emoji: string; color: string }[] = [
  { value: 'active', label: 'Pendiente de verificacion', emoji: '🟡', color: '#eab308' },
  { value: 'in_progress', label: 'En proceso de ayuda', emoji: '🔵', color: '#3b82f6' },
  { value: 'resolved', label: 'Resuelto', emoji: '🟢', color: '#22c55e' },
  { value: 'closed', label: 'Cerrado', emoji: '⚫', color: '#6b7280' },
]

export const MAP_COLORS: Record<string, string> = {
  help_request: '#dc2626',
  help_offer: '#22c55e',
  person_found: '#3b82f6',
  incident: '#f97316',
  shelter: '#eab308',
  hospital: '#3b82f6',
  medical_center: '#a855f7',
  community_kitchen: '#f97316',
  collection_center: '#92400e',
  danger_zone: '#1f2937',
  blocked_road: '#9ca3af',
  protection: '#a855f7',
  health_request: '#e11d48',
  campaign: '#8b5cf6',
}

export const MAP_LABELS: Record<string, string> = {
  help_request: 'Necesitan ayuda',
  help_offer: 'Ofrecen ayuda',
  person_found: 'Personas',
  incident: 'Incidentes',
  shelter: 'Refugios',
  hospital: 'Hospitales',
  medical_center: 'Centros medicos',
  community_kitchen: 'Cocinas comunitarias',
  collection_center: 'Centros de acopio',
  danger_zone: 'Zonas peligrosas',
  blocked_road: 'Calles bloqueadas',
  protection: 'Proteccion y rescate',
  health_request: 'Solicitudes de salud',
  campaign: 'Campanas verificadas',
}

export const MARKER_ICONS: Record<string, { emoji: string; bg: string }> = {
  help_request: { emoji: '🆘', bg: '#dc2626' },
  help_offer: { emoji: '❤️', bg: '#16a34a' },
  person_found: { emoji: '👤', bg: '#2563eb' },
  incident: { emoji: '⚠️', bg: '#ea580c' },
  shelter: { emoji: '🏠', bg: '#ca8a04' },
  collection_center: { emoji: '📦', bg: '#92400e' },
  hospital: { emoji: '🏥', bg: '#7c3aed' },
  danger_zone: { emoji: '☠️', bg: '#374151' },
  protection: { emoji: '🛡️', bg: '#9333ea' },
  health_request: { emoji: '❤️', bg: '#e11d48' },
  campaign: { emoji: '📢', bg: '#8b5cf6' },
}

export const POI_TYPE_MAP: Record<PoiType, { color: string; label: string }> = {
  shelter: { color: '#eab308', label: 'Refugio' },
  hospital: { color: '#3b82f6', label: 'Hospital' },
  medical_center: { color: '#a855f7', label: 'Centro medico' },
  community_kitchen: { color: '#f97316', label: 'Cocina comunitaria' },
  collection_center: { color: '#92400e', label: 'Centro de acopio' },
  danger_zone: { color: '#1f2937', label: 'Zona peligrosa' },
  blocked_road: { color: '#9ca3af', label: 'Calle bloqueada' },
  incident: { color: '#ea580c', label: 'Incidente' },
  protection: { color: '#a855f7', label: 'Proteccion y rescate' },
  health_request: { color: '#e11d48', label: 'Solicitud de salud' },
}

export const CITIES = ['Caracas', 'La Guaira', 'Guarenas', 'Guatire', 'Los Teques']

export const DEFAULT_CENTER = { lat: 10.4806, lng: -66.9036 }
export const DEFAULT_ZOOM = 12

export const LABEL_ES: Record<string, string> = {
  water: 'Agua',
  food: 'Alimentos',
  medicine: 'Medicamentos',
  shelter: 'Refugio',
  rescue: 'Rescate',
  electricity: 'Electricidad',
  communication: 'Comunicacion',
  transport: 'Transporte',
  kitchen: 'Cocina',
  gas: 'Gas',
  vehicle: 'Transporte',
  fuel: 'Combustible',
  tools: 'Herramientas',
  internet: 'Internet',
  starlink: 'Starlink',
  generator: 'Generador',
  doctor: 'Medico',
  nurse: 'Enfermero/a',
  psychologist: 'Psicologo/a',
  rescuers: 'Rescatistas',
  volunteers: 'Voluntarios',
  shelter_space: 'Espacio para alojar',
  clothing: 'Ropa',
  machinery: 'Maquinaria',
  other: 'Otro',
  pending: 'Pendiente',
  in_process: 'En proceso',
  in_progress: 'En proceso de ayuda',
  attended: 'Atendido',
  resolved: 'Resuelto',
  closed: 'Cerrado',
  active: 'Activo',
  available: 'Disponible',
  ok: 'Bien',
  injured: 'Herido/a',
  medical_attention: 'Atencion medica',
  transferred: 'Trasladado/a',
  with_family: 'Con familiares',
  unknown: 'Desconocido',
  low: 'Baja',
  medium: 'Media',
  high: 'Alta',
  critical: 'Critica',
  child_at_risk: 'Menor en riesgo',
  elderly_at_risk: 'Adulto mayor en riesgo',
  disabled_at_risk: 'Persona con discapacidad en riesgo',
  disoriented_person: 'Persona desorientada',
  vulnerable_immediate: 'Ayuda inmediata',
  lost_pet: 'Mascota perdida',
  found_pet: 'Mascota encontrada',
  animal_at_risk: 'Animal en riesgo',
  alone: 'Solo/a',
  needs_help: 'Necesita ayuda',
  disoriented: 'Desorientado/a',
  accompanied: 'Acompanado/a',
  protection: 'Proteccion y rescate',
  health_request: 'Solicitud de salud',
  blood_donors: 'Donantes de sangre',
  platelet_donors: 'Donantes de plaquetas',
  medication: 'Medicamentos urgentes',
  oxygen: 'Oxigeno',
  medical_supplies: 'Insumos medicos',
  medical_equipment: 'Equipos medicos',
  infant_formula: 'Formula infantil',
  breast_milk: 'Leche materna',
  searching: 'Buscando ayuda',
  donors_confirmed: 'Donantes confirmados',
  cooks: 'Cocineros',
  food_supplies: 'Alimentos',
  utensils: 'Utensilios',
  firewood: 'Lena',
}

export const TYPE_ICONS: Record<string, string> = {
  water: '💧',
  food: '🍞',
  medicine: '💊',
  shelter: '🏠',
  rescue: '🚑',
  electricity: '⚡',
  communication: '📡',
  transport: '🚗',
  kitchen: '🍳',
  gas: '🔥',
  vehicle: '🚗',
  fuel: '⛽',
  tools: '🔧',
  internet: '📶',
  starlink: '🛰️',
  generator: '🔋',
  doctor: '👨‍⚕️',
  nurse: '👩‍⚕️',
  psychologist: '🧠',
  rescuers: '🚒',
  volunteers: '🤝',
  shelter_space: '🏠',
  clothing: '👕',
  machinery: '🏗️',
  other: '📋',
  child_at_risk: '👶',
  elderly_at_risk: '👴',
  disabled_at_risk: '♿',
  disoriented_person: '🧭',
  vulnerable_immediate: '🚨',
  lost_pet: '🐶',
  found_pet: '🐕',
  animal_at_risk: '🐾',
  protection: '🛡️',
  health_request: '❤️',
  blood_donors: '🩸',
  platelet_donors: '🧬',
  medication: '💊',
  oxygen: '🫁',
  medical_supplies: '🩺',
  medical_equipment: '🦽',
  infant_formula: '👶',
  breast_milk: '🍼',
  cooks: '🍲',
  food_supplies: '🥘',
  utensils: '🥄',
  firewood: '🪵',
}

export const HEALTH_REQUEST_TYPES: { value: HealthRequestType; label: string; icon: string }[] = [
  { value: 'blood_donors', label: 'Donantes de sangre', icon: '🩸' },
  { value: 'platelet_donors', label: 'Donantes de plaquetas', icon: '🧬' },
  { value: 'medication', label: 'Medicamentos urgentes', icon: '💊' },
  { value: 'oxygen', label: 'Oxigeno', icon: '🫁' },
  { value: 'medical_supplies', label: 'Insumos medicos', icon: '🩺' },
  { value: 'medical_equipment', label: 'Equipos medicos', icon: '🦽' },
  { value: 'infant_formula', label: 'Formula infantil', icon: '👶' },
  { value: 'breast_milk', label: 'Leche materna', icon: '🍼' },
  { value: 'other', label: 'Otro', icon: '📋' },
]

export const BLOOD_TYPES: { value: BloodType; label: string }[] = [
  { value: 'A+', label: 'A+' },
  { value: 'A-', label: 'A-' },
  { value: 'B+', label: 'B+' },
  { value: 'B-', label: 'B-' },
  { value: 'AB+', label: 'AB+' },
  { value: 'AB-', label: 'AB-' },
  { value: 'O+', label: 'O+' },
  { value: 'O-', label: 'O-' },
  { value: 'not_applicable', label: 'No aplica' },
]

export const HEALTH_REQUEST_STATUSES: { value: string; label: string; emoji: string; color: string }[] = [
  { value: 'searching', label: 'Buscando ayuda', emoji: '🟡', color: '#eab308' },
  { value: 'donors_confirmed', label: 'Donantes confirmados', emoji: '🔵', color: '#3b82f6' },
  { value: 'resolved', label: 'Resuelto', emoji: '🟢', color: '#22c55e' },
  { value: 'closed', label: 'Cerrado', emoji: '⚫', color: '#6b7280' },
]

export const HEALTH_PRIORITIES: { value: HealthPriority; label: string; emoji: string; color: string }[] = [
  { value: 'critical', label: 'Critica', emoji: '🔴', color: '#dc2626' },
  { value: 'high', label: 'Alta', emoji: '🟠', color: '#f97316' },
  { value: 'medium', label: 'Media', emoji: '🟡', color: '#eab308' },
  { value: 'low', label: 'Baja', emoji: '🟢', color: '#22c55e' },
]

export const COMMUNITY_KITCHEN_NEEDS: { value: CommunityKitchenNeedType; label: string; icon: string }[] = [
  { value: 'cooks', label: 'Se necesitan cocineros', icon: '🍲' },
  { value: 'food_supplies', label: 'Se necesitan alimentos', icon: '🥘' },
  { value: 'utensils', label: 'Se necesitan utensilios', icon: '🥄' },
  { value: 'gas', label: 'Se necesita gas', icon: '🔥' },
  { value: 'firewood', label: 'Se necesita lena', icon: '🪵' },
  { value: 'volunteers', label: 'Se necesitan voluntarios', icon: '🤝' },
  { value: 'other', label: 'Otro', icon: '📋' },
]

export const CAMPAIGN_TYPES: { value: CampaignType; label: string; icon: string }[] = [
  { value: 'blood_donation', label: 'Donacion de sangre', icon: '🩸' },
  { value: 'medical_day', label: 'Jornada medica', icon: '🏥' },
  { value: 'vaccination', label: 'Vacunacion', icon: '💉' },
  { value: 'food_collection', label: 'Recoleccion de alimentos', icon: '🍲' },
  { value: 'water_distribution', label: 'Distribucion de agua', icon: '💧' },
  { value: 'medicine_delivery', label: 'Entrega de medicamentos', icon: '💊' },
  { value: 'rescue', label: 'Jornada de rescate', icon: '🚑' },
  { value: 'community_kitchen', label: 'Olla comunitaria', icon: '🍲' },
  { value: 'government', label: 'Campana gubernamental', icon: '🏛️' },
  { value: 'ngo', label: 'Campana de ONG', icon: '🤝' },
  { value: 'general', label: 'General', icon: '📢' },
]

export const VERIFICATION_LEVELS: { value: VerificationLevel; label: string; emoji: string; color: string }[] = [
  { value: 'unverified', label: 'Sin verificar', emoji: '⚪', color: '#6b7280' },
  { value: 'community', label: 'Verificada por la comunidad', emoji: '🟡', color: '#eab308' },
  { value: 'nodo', label: 'Verificada por NODO', emoji: '🟢', color: '#22c55e' },
  { value: 'official', label: 'Fuente oficial', emoji: '🔵', color: '#3b82f6' },
]

export const KNOWN_HOSPITALS: string[] = [
  'Hospital Universitario de Caracas',
  'Hospital Vargas de Caracas',
  'Hospital de Clinicas Caracas',
  'Hospital Miguel Perez Carreno',
  'Hospital J.M. de los Rios',
  'Hospital Domingo Luciani',
  'Hospital Dr. Jose Ignacio Baldo',
  'Hospital Central de Maracay',
  'Hospital Universitario de Maracaibo',
  'Hospital Central de San Cristobal',
  'Hospital Universitario Dr. Angel Larralde',
  'Hospital General del Oeste Dr. Jose Gregorio Hernandez',
  'Hospital Dr. Jose Maria Vargas',
  'Hospital General de Barquisimeto',
  'Clinica Santa Sofia',
  'Clinica El Avila',
  'Clinica Metropolitana',
  'Policlinica Metropolitana',
  'Centro Medico de Caracas',
  'Centro Medico Docente La Trinidad',
  'Hospital Militar Dr. Carlos Arvelo',
  'Hospital de Ninos J.M. de los Rios',
  'Maternidad Concepcion Palacios',
]
