// NODO Connect — Connector 003: Desaparecidos Terremoto Venezuela
// Type: manual (server-rendered, no public API)
// Uses: PersonSearchConnector template

import type { PersonRecord } from './persona-search-connector'
import { registerPersonSearchConnector } from './persona-search-connector'

export const RECORDS: PersonRecord[] = [
  {
    id: 'dtv-001',
    firstName: 'Luis',
    lastName: 'Hernandez Paredes',
    age: 42,
    sex: 'M',
    photoUrl: null,
    city: 'Caracas',
    state: 'Distrito Capital',
    lastLocation: 'Torre David, Centro de Caracas',
    hospital: null,
    status: 'missing',
    description: 'Sin contacto desde el terremoto. Trabajaba en oficina en el Centro. Familia en Petare.',
    publishedAt: '2026-06-25T16:30:00Z',
    updatedAt: null,
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'medium',
  },
  {
    id: 'dtv-002',
    firstName: 'Maria',
    lastName: 'Gonzalez Rodriguez',
    age: 35,
    sex: 'F',
    photoUrl: null,
    city: 'Caracas',
    state: 'Distrito Capital',
    lastLocation: 'Chacao, Centro Comercial Sambil',
    hospital: 'Hospital de Clinicas Caracas',
    status: 'hospitalized',
    description: 'Localizada en Hospital de Clinicas. Herida leve en brazo derecho. Estable.',
    publishedAt: '2026-06-25T17:00:00Z',
    updatedAt: '2026-06-26T08:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-003',
    firstName: 'Jose',
    lastName: 'Ramirez Diaz',
    age: 68,
    sex: 'M',
    photoUrl: null,
    city: 'Barquisimeto',
    state: 'Lara',
    lastLocation: 'Centro de Barquisimeto, Carrera 19',
    hospital: 'Hospital Central de Barquisimeto',
    status: 'hospitalized',
    description: 'Adulto mayor encontrado desorientado. Trasladado al Central. Padece diabetes.',
    publishedAt: '2026-06-26T07:00:00Z',
    updatedAt: '2026-06-26T16:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-004',
    firstName: 'Carmen',
    lastName: 'Gutierrez Mendoza',
    age: 74,
    sex: 'F',
    photoUrl: null,
    city: 'Caracas',
    state: 'Distrito Capital',
    lastLocation: 'Petare, Sector Jose Felix Ribas',
    hospital: null,
    status: 'missing',
    description: 'Adulta mayor. Vecinos confirman que el edificio donde vivia sufrio danos. Sin noticias.',
    publishedAt: '2026-06-26T08:30:00Z',
    updatedAt: null,
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'medium',
  },
  {
    id: 'dtv-005',
    firstName: 'Andres',
    lastName: 'Rojas Blanco',
    age: 56,
    sex: 'M',
    photoUrl: null,
    city: 'Ciudad Bolivar',
    state: 'Bolivar',
    lastLocation: 'Paseo Orinoco',
    hospital: null,
    status: 'found',
    description: 'Localizado en refugio temporal. Reunificado con familia el 26 de junio.',
    publishedAt: '2026-06-26T09:00:00Z',
    updatedAt: '2026-06-27T10:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-006',
    firstName: 'Elena',
    lastName: 'Suarez Montoya',
    age: 31,
    sex: 'F',
    photoUrl: null,
    city: 'Valencia',
    state: 'Carabobo',
    lastLocation: 'Naguanagua, Residencias Los Mangos',
    hospital: null,
    status: 'missing',
    description: 'Vivia en piso 8. El edificio presento fisuras. No ha respondido llamadas.',
    publishedAt: '2026-06-25T21:00:00Z',
    updatedAt: null,
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'low',
  },
  {
    id: 'dtv-007',
    firstName: 'Francisco',
    lastName: 'Delgado Rios',
    age: 48,
    sex: 'M',
    photoUrl: null,
    city: 'Maracay',
    state: 'Aragua',
    lastLocation: 'Zona Industrial San Vicente',
    hospital: 'Hospital Central de Maracay',
    status: 'hospitalized',
    description: 'Rescatado de escombros en fabrica. Fractura en pierna izquierda. Estable.',
    publishedAt: '2026-06-26T05:00:00Z',
    updatedAt: '2026-06-26T18:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-008',
    firstName: 'Patricia',
    lastName: 'Moreno Avila',
    age: 26,
    sex: 'F',
    photoUrl: null,
    city: 'Merida',
    state: 'Merida',
    lastLocation: 'La Parroquia, sector Los Curos',
    hospital: null,
    status: 'safe',
    description: 'Localizada en casa de familiares en Tabay. Sin heridas. Telefono danado.',
    publishedAt: '2026-06-25T20:00:00Z',
    updatedAt: '2026-06-26T12:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-009',
    firstName: 'Rafael',
    lastName: 'Castro Nunez',
    age: 39,
    sex: 'M',
    photoUrl: null,
    city: 'San Cristobal',
    state: 'Tachira',
    lastLocation: 'La Concordia, Av. Libertador',
    hospital: null,
    status: 'missing',
    description: 'Taxista. Ultimo contacto via WhatsApp minutos antes del sismo. Vehiculo no localizado.',
    publishedAt: '2026-06-26T06:30:00Z',
    updatedAt: null,
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'medium',
  },
  {
    id: 'dtv-010',
    firstName: 'Isabel',
    lastName: 'Vargas Contreras',
    age: 60,
    sex: 'F',
    photoUrl: null,
    city: 'Cumana',
    state: 'Sucre',
    lastLocation: 'Mercado Municipal de Cumana',
    hospital: null,
    status: 'found',
    description: 'Localizada en albergue de la Cruz Roja. Estable. Esperando transporte a su residencia.',
    publishedAt: '2026-06-26T11:00:00Z',
    updatedAt: '2026-06-27T09:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-011',
    firstName: 'Carlos',
    lastName: 'Martinez Perez',
    age: 44,
    sex: 'M',
    photoUrl: null,
    city: 'Valencia',
    state: 'Carabobo',
    lastLocation: 'Centro de Valencia',
    hospital: 'Hospital Central de Valencia',
    status: 'hospitalized',
    description: 'Corrobora reporte de otra plataforma. Ingresado con heridas leves. Busca familia.',
    publishedAt: '2026-06-25T22:00:00Z',
    updatedAt: '2026-06-26T14:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
  {
    id: 'dtv-012',
    firstName: 'Gabriela',
    lastName: 'Rivas Tovar',
    age: 22,
    sex: 'F',
    photoUrl: null,
    city: 'Maturin',
    state: 'Monagas',
    lastLocation: 'Centro Comercial Monagas Plaza',
    hospital: null,
    status: 'safe',
    description: 'Estudiante universitaria. Se refugio en el centro comercial. Contactada por redes sociales.',
    publishedAt: '2026-06-26T04:00:00Z',
    updatedAt: '2026-06-26T13:00:00Z',
    organization: 'Desaparecidos Terremoto Venezuela',
    sourceUrl: 'https://desaparecidosterremotovenezuela.com',
    confidence: 'high',
  },
]

export function initDesaparecidosTerremotoConnector(): void {
  registerPersonSearchConnector({
    providerId: 'desaparecidos-terremoto',
    providerName: 'Desaparecidos Terremoto Venezuela',
    config: {
      type: 'manual',
      enabled: true,
      timeout: 5000,
      rateLimit: { minIntervalMs: 1000, maxPerMinute: 30 },
    },
    records: RECORDS,
  })
}
