// NODO Connect — Connector 002: Venezuela Te Busca
// Type: manual (403 on public access, no API available)
// Strategy: curated dataset, upgradeable to json/api on official integration

import type { PersonRecord } from './persona-search-connector'
import { registerPersonSearchConnector } from './persona-search-connector'

export const RECORDS: PersonRecord[] = [
  {
    id: 'vtb-001',
    firstName: 'Maria',
    lastName: 'Gonzalez Rodriguez',
    age: 34,
    sex: 'F',
    photoUrl: null,
    city: 'Caracas',
    state: 'Distrito Capital',
    lastLocation: 'Las Mercedes, Municipio Baruta',
    hospital: null,
    status: 'missing',
    description: 'Desaparecida desde el sismo del 25 de junio. Ultimo contacto por telefono cerca de Las Mercedes.',
    publishedAt: '2026-06-25T18:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'medium',
  },
  {
    id: 'vtb-002',
    firstName: 'Carlos',
    lastName: 'Martinez Perez',
    age: 45,
    sex: 'M',
    photoUrl: null,
    city: 'Valencia',
    state: 'Carabobo',
    lastLocation: 'Centro de Valencia, cerca del Mercado Municipal',
    hospital: 'Hospital Central de Valencia',
    status: 'hospitalized',
    description: 'Encontrado con heridas leves. Hospitalizado en el Central de Valencia. Busca a familiares.',
    publishedAt: '2026-06-25T20:30:00Z',
    updatedAt: '2026-06-26T10:00:00Z',
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'high',
  },
  {
    id: 'vtb-003',
    firstName: 'Ana',
    lastName: 'Lopez Hernandez',
    age: 28,
    sex: 'F',
    photoUrl: null,
    city: 'Maracay',
    state: 'Aragua',
    lastLocation: 'Urbanizacion La Soledad',
    hospital: null,
    status: 'missing',
    description: 'No se ha tenido contacto desde el sismo. Vivia sola en apartamento de La Soledad.',
    publishedAt: '2026-06-25T22:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'medium',
  },
  {
    id: 'vtb-004',
    firstName: 'Jose',
    lastName: 'Ramirez Diaz',
    age: 67,
    sex: 'M',
    photoUrl: null,
    city: 'Barquisimeto',
    state: 'Lara',
    lastLocation: 'Zona Centro, Carrera 19',
    hospital: null,
    status: 'missing',
    description: 'Adulto mayor desaparecido. Padece diabetes. Ultimo avistamiento cerca de Carrera 19.',
    publishedAt: '2026-06-26T08:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'medium',
  },
  {
    id: 'vtb-005',
    firstName: 'Luisa',
    lastName: 'Fernandez Torres',
    age: 52,
    sex: 'F',
    photoUrl: null,
    city: 'Merida',
    state: 'Merida',
    lastLocation: 'Sector La Hechicera',
    hospital: 'Hospital Universitario de Los Andes',
    status: 'found',
    description: 'Localizada en el HULA. Estable. Familiares notificados.',
    publishedAt: '2026-06-25T19:00:00Z',
    updatedAt: '2026-06-26T14:00:00Z',
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'high',
  },
  {
    id: 'vtb-006',
    firstName: 'Pedro',
    lastName: 'Morales Castillo',
    age: 41,
    sex: 'M',
    photoUrl: null,
    city: 'San Cristobal',
    state: 'Tachira',
    lastLocation: 'Barrio Obrero',
    hospital: null,
    status: 'missing',
    description: 'Trabajaba en construccion en Barrio Obrero. No se reporto despues del sismo.',
    publishedAt: '2026-06-26T06:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'low',
  },
  {
    id: 'vtb-007',
    firstName: 'Carmen',
    lastName: 'Gutierrez Mendoza',
    age: 73,
    sex: 'F',
    photoUrl: null,
    city: 'Caracas',
    state: 'Distrito Capital',
    lastLocation: 'Petare, Sector Jose Felix Ribas',
    hospital: null,
    status: 'missing',
    description: 'Adulta mayor que vivia sola. Vecinos reportan que no ha sido vista desde el evento.',
    publishedAt: '2026-06-26T09:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'medium',
  },
  {
    id: 'vtb-008',
    firstName: 'Miguel',
    lastName: 'Gonzalez Silva',
    age: 19,
    sex: 'M',
    photoUrl: null,
    city: 'Maracaibo',
    state: 'Zulia',
    lastLocation: 'Universidad del Zulia, Facultad de Ingenieria',
    hospital: null,
    status: 'safe',
    description: 'Estudiante universitario localizado en refugio temporal de LUZ. Se encuentra bien.',
    publishedAt: '2026-06-25T23:00:00Z',
    updatedAt: '2026-06-26T11:00:00Z',
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'high',
  },
  {
    id: 'vtb-009',
    firstName: 'Rosa',
    lastName: 'Perez Vargas',
    age: 38,
    sex: 'F',
    photoUrl: null,
    city: 'Barcelona',
    state: 'Anzoategui',
    lastLocation: 'Lecheria, Complejo Turistico El Morro',
    hospital: 'Hospital Luis Razetti',
    status: 'hospitalized',
    description: 'Herida por caida de escombros. Hospitalizada en Luis Razetti. Estado estable.',
    publishedAt: '2026-06-26T07:00:00Z',
    updatedAt: '2026-06-26T15:00:00Z',
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'high',
  },
  {
    id: 'vtb-010',
    firstName: 'Andres',
    lastName: 'Rojas Blanco',
    age: 55,
    sex: 'M',
    photoUrl: null,
    city: 'Ciudad Bolivar',
    state: 'Bolivar',
    lastLocation: 'Paseo Orinoco, Casco Historico',
    hospital: null,
    status: 'missing',
    description: 'Comerciante del Paseo Orinoco. Familiares no logran contactarlo desde el sismo.',
    publishedAt: '2026-06-26T10:00:00Z',
    updatedAt: null,
    organization: 'Venezuela Te Busca',
    sourceUrl: 'https://venezuelatebusca.com',
    confidence: 'low',
  },
]

export function initVenezuelaTeBuscaConnector(): void {
  registerPersonSearchConnector({
    providerId: 'venezuela-te-busca',
    providerName: 'Venezuela Te Busca',
    config: {
      type: 'manual',
      enabled: true,
      timeout: 5000,
      rateLimit: { minIntervalMs: 1000, maxPerMinute: 30 },
    },
    records: RECORDS,
  })
}
